### PR TITLE
feat: add settings support

### PR DESCRIPTION
**Pull request by babydragon**
Hi, 
Our team use private maven repo and I'm now use maven-settings-xml-action to generate settings file.
This PR add a parameter to support define the location of settings file

### CODE REVIEW

**Comment by JarvisCraft** [comment]
Hi!

This enhancement looks great, thanks for your PR.

I suggest trying to use one of the techniques described [here](https://github.com/orgs/community/discussions/26738) to implement a pseudo-ternary operator in order not to produce an extra job step.
What I mean is something effectively similar to `${{ inputs.settings }} ? ${{ inputs.settings }} : ''`.
Also, please consider using the same style for the variables, i.e. spaces inside of curly brackets.

**Comment by JarvisCraft** [comment]
Please tag me once the cnahges are ready for review :)

**Comment by babydragon** [comment]
Sorry I'm new to action, just remove the step and use pseudo-ternary operator.

**Comment by JarvisCraft** [comment]
No problem! I will test the changes and apply them ASAP

**Comment by JarvisCraft** [comment]
Thanks for the contribution!

**Pull request merged**
